import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Kanban Board",
  description:
    "Generated by your and only Niraj Pujari, Just a simple task manager",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">{children}
        <Toaster theme="dark" duration={3000} closeButton position="bottom-right" />
      </body>
    </html>
    
  );
}
